import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Bell, Search, Settings, ChevronDown, ArrowUpRight, Clock3, Activity, Sparkles, ShieldAlert, Radio, Command, ChevronRight, CircleHelp } from 'lucide-react';
import { getMarketSnapshot, type Freshness } from './lib/api';
import './styles.css';

type Tone = 'up' | 'down' | 'neutral';
type Instrument = {name:string; symbol:string; price:string; change:string; tone:Tone; status:Freshness};
const instruments: Instrument[] = [
  { name:'NIFTY 50', symbol:'NSE:NIFTY50', price:'—', change:'Data unavailable', tone:'neutral', status:'UNAVAILABLE' },
  { name:'BANK NIFTY', symbol:'NSE:BANKNIFTY', price:'—', change:'Data unavailable', tone:'neutral', status:'UNAVAILABLE' },
  { name:'INDIA VIX', symbol:'NSE:INDIAVIX', price:'—', change:'Data unavailable', tone:'neutral', status:'UNAVAILABLE' },
  { name:'USD / INR', symbol:'FX:USDINR', price:'—', change:'Data unavailable', tone:'neutral', status:'UNAVAILABLE' },
  { name:'GOLD', symbol:'MCX:GOLD', price:'—', change:'Data unavailable', tone:'neutral', status:'UNAVAILABLE' },
];
type MarketEvent = { impact: 'HIGH' | 'MEDIUM'; dir: 'MIXED' | 'POSITIVE' | 'UNCERTAIN'; title: string; meta: string; copy: string; sources: number };
const events: MarketEvent[] = [];
const sectors = ['Financials', 'IT', 'Energy', 'Auto', 'Metals', 'Pharma', 'FMCG', 'Realty'];
function MarketCard({x}:{x:Instrument}) { return <article className="market-card"><div className="row"><div><p className="eyebrow">{x.symbol}</p><h3>{x.name}</h3></div><span className={`status ${x.status === 'UNAVAILABLE' ? 'unavailable' : ''}`}>{x.status}</span></div><div className="price-row"><strong>{x.status === 'UNAVAILABLE' ? '—' : x.price}</strong><span className={x.tone}>{x.change}</span></div><div className="spark"><i className={x.tone}></i><i className={x.tone}></i><i className={x.tone}></i><i className={x.tone}></i><i className={x.tone}></i><i className={x.tone}></i><i className={x.tone}></i></div><p className="fresh"><Clock3 size={12}/> Updated 2m ago · {x.status === 'UNAVAILABLE' ? 'No licensed feed connected' : 'Delayed source'}</p></article> }
function App(){ const [mode,setMode]=useState<'BEGINNER'|'PRO'>('PRO'); const [seconds,setSeconds]=useState(68*60+24); const [active,setActive]=useState('Home'); const [marketData,setMarketData]=useState<Instrument[]>(instruments); useEffect(()=>{const id=setInterval(()=>setSeconds(v=>v-1),1000);return()=>clearInterval(id)},[]); useEffect(()=>{const controller=new AbortController(); Promise.all(instruments.map(async instrument=>{try { const snapshot=await getMarketSnapshot(instrument.symbol,controller.signal); return {...instrument,status:snapshot.freshness,change:snapshot.message}; } catch { return instrument; }})).then(setMarketData); return()=>controller.abort();},[]); const hh=String(Math.max(0,Math.floor(seconds/3600))).padStart(2,'0'), mm=String(Math.max(0,Math.floor(seconds%3600/60))).padStart(2,'0'), ss=String(Math.max(0,seconds%60)).padStart(2,'0'); return <div className="app">
  <aside><div className="brand"><span className="brand-mark">B</span><span>BHARAT<span>IQ</span></span></div><div className="workspace"><span>WORKSPACE</span><button><Command size={13}/> Command Center <ChevronDown size={13}/></button></div><nav>{['Home','Markets','Pre-Market','Live Market','News','Analysis','Options','FII / DII','Institutional','Block / Bulk Deals','IPO','Corporate Actions','Earnings','Economic Calendar','Screener','Watchlist','Portfolio','Trade Journal','Backtest','AI Copilot'].map(n=><button onClick={()=>setActive(n)} className={active===n?'active':''} key={n}>{n==='Home'?<Activity size={16}/>:n==='AI Copilot'?<Sparkles size={16}/>:<span className="nav-dot"/>}{n}{n==='Pre-Market'&&<b>NEW</b>}</button>)}</nav><div className="side-bottom"><button><CircleHelp size={16}/> Help & education</button><button><Settings size={16}/> Settings</button><p>Data governance enabled<br/><span>Build 0.1 · Phase 1</span></p></div></aside>
  <main><header><div className="mobile-brand">BHARAT<span>IQ</span></div><button className="search"><Search size={17}/><span>Search companies, events, sectors...</span><kbd>/</kbd></button><div className="top-actions"><button className="mode" onClick={()=>setMode(mode==='PRO'?'BEGINNER':'PRO')}>{mode} <ChevronDown size={14}/></button><button className="icon"><Bell size={18}/><i/></button><button className="avatar">AS</button></div></header>
  <section className="intro"><div><div className="section-label"><Radio size={13}/> PRE-MARKET COMMAND CENTER</div><h1>Good morning, Arjun.</h1><p>Here is the verified context before India opens. <strong>Interpretation is labeled separately from facts.</strong></p></div><div className="session"><span className="pulse"/> <div><b>Equities pre-open</b><small>NSE cash market opens in</small></div><strong>{hh}:{mm}:{ss}</strong><button>Market calendar <ChevronRight size={14}/></button></div></section>
  <section className="metrics">{marketData.map(x=><MarketCard key={x.name} x={x}/>)}</section>
  <section className="grid"><div className="panel matters"><div className="panel-title"><div><span className="section-label ai"><Sparkles size={13}/> AI PRIORITIZED</span><h2>What matters today?</h2><p>Ranked events since yesterday’s Indian market close.</p></div><button className="link">View all events <ArrowUpRight size={14}/></button></div>{events.length === 0 ? <div className="empty evidence-empty"><Activity size={22}/><b>No verified events available</b><p>Connect approved, licensed news and exchange sources to populate this feed.</p></div> : events.map(e=><article className="event" key={e.title}><div className={`impact ${e.impact.toLowerCase()}`}>{e.impact}</div><div className="event-content"><div><span className={`direction ${e.dir.toLowerCase()}`}>{e.dir}</span><h3>{e.title}</h3></div><p>{e.copy}</p><footer><span>{e.meta}</span><span>Evidence: {e.sources} sources</span><a href="#sources">View sources <ArrowUpRight size={12}/></a></footer></div></article>)}<div className="disclosure"><ShieldAlert size={15}/><span><b>Analysis boundary:</b> No live prices are fabricated. Connected provider data is required before a status can be LIVE.</span><a href="#method">Methodology</a></div></div>
  <div className="right-col"><section className="panel sector"><div className="panel-title"><div><h2>Sector pulse</h2><p>Relative move · latest available</p></div><button className="icon-lite"><ChevronRight size={16}/></button></div><div className="sector-grid">{sectors.map(name=><div className="sector-item neutral" key={name}><span>{name}</span><b>—</b><div><i style={{width:'0%'}}/></div></div>)}</div><p className="footnote">Data unavailable until an approved market-data provider is connected.</p></section>
  <section className="panel radar"><div className="panel-title"><div><span className="section-label warning"><ShieldAlert size={13}/> SCHEDULED</span><h2>Risk & catalyst radar</h2></div><button className="link">Calendar <ArrowUpRight size={14}/></button></div><div className="empty"><Activity size={22}/><b>No scheduled events available</b><p>Connect an approved economic-calendar source to populate the risk and catalyst radar.</p></div></section></div></section>
  <section className="bottom-grid"><div className="panel setup"><div className="panel-title"><div><span className="section-label"><Sparkles size={13}/> MORNING BRIEF</span><h2>India setup</h2></div><button className="link">Open full brief <ArrowUpRight size={14}/></button></div><div className="brief-columns"><div><b>FACTS</b><p>Market data remains clearly labeled by source freshness and entitlement.</p></div><div><b>ANALYSIS</b><p>Evidence points to mixed global context; direction is <em>uncertain</em> until verified inputs arrive.</p></div><div><b>HISTORICAL CONTEXT</b><p>Data unavailable until a licensed historical dataset is configured.</p></div></div></div><div className="panel activity"><div className="panel-title"><div><h2>Live event stream</h2><p>Awaiting connected providers</p></div><span className="status unavailable">UNAVAILABLE</span></div><div className="empty"><Activity size={22}/><b>No provider events yet</b><p>Connect an approved source in Settings. The terminal will never substitute placeholders for live market data.</p></div></div></section>
  </main></div> }
createRoot(document.getElementById('root')!).render(<App/>);
